Fix TS typings for component.create(), broken by 4b15771
Resolves error TS2425: Class 'Component' defines instance member property 'create', but extended class 'MyComponent' defines it as instance member function.